### ISSUE TITLE
bootstrap Errors

### ISSUE THREAD

**Issue by fisher2834** [ccman32/FireRTCCallerIDChanger#2]
This error happens when I click "Change CallerID" my username on discord is "Discord Dailer" Is the space an issue?

Unable to open file: C:\Users\Discord

  phantomjs://code/bootstrap.js:113 in die
Unable to load script C:\Users\Discord; check file syntax

  phantomjs://code/bootstrap.js:113 in die

**Comment by fisher2834** [comment]
I can confirm I made a new user on Windows without a space in the username and its working fine now.

**Comment by ccman32** [comment]
I'll check if thats an error on my end or if its a problem in any of the other software components that I use.

**Comment by ccman32** [comment]
@fisher2834 sorry for the delay. I recently helped someone else who had the same problem and it could be fixed by removing the space in his username. However, this seems to be a problem in PhantomJS.
If you want, you can try raising an issue on the PhantomJS github page - https://github.com/ariya/phantomjs/issues

Please let me know if you would like to continue further by raising an issue on the PhantomJS github page or if this issue can be closed because you got it to work on another windows user.

**Comment by ccman32** [comment]
I will close this issue now because no further replies have been made.
